semjidhapp/semjidhapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from viagens import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('viagens/', include('viagens.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
]

semjidhapp/viagens/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('listar_viagens/', views.listar_viagens, name='listar_viagens'),
    path('solicitar_viagem/', views.solicitar_viagem, name='solicitar_viagem'),
    path('designar_motorista/<int:viagem_id>/', views.designar_motorista, name='designar_motorista'),
    path('cadastrar_motorista/', views.cadastrar_motorista, name='cadastrar_motorista'),
    path('listar_motoristas/', views.listar_motoristas, name='listar_motoristas'),
    path('<int:id>/apagar/', views.apagar_viagem, name='apagar_viagem'),
    path('motorista/<int:id>/apagar/', views.apagar_motorista, name='apagar_motorista'),
    path('exportar_viagens/', views.exportar_viagens, name='exportar_viagens'),
    path('listar_carros/', views.listar_carros, name='listar_carros'),
    path('carro/<int:id>/apagar/', views.apagar_carro, name='apagar_carro'),
    path('cadastrar_carro/', views.cadastrar_carro, name='cadastrar_carro'),
    path('designar_carro/<int:viagem_id>/', views.designar_carro, name='designar_carro'),
]

semjidhapp/viagens/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Carro(models.Model):
    marca = models.CharField(max_length=20)
    modelo = models.CharField(max_length=30)
    placa = models.CharField(max_length=7)

    def __str__(self):
        return f"{self.marca} {self.modelo} - {self.placa}"

class Motorista(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.nome

class Viagem(models.Model):

    SETOR_CHOICES = [
        ('Gabinete',   'Gabinete'),
        ('Comunicação','Comunicação'),
        ('Adjunto',    'Adjunto'),
        ('Ouvidoria',  'Ouvidoria'),
        ('Procon',     'Procon'),
        ('CODIS',      'CODIS'),
        ('COEPPIR',    'COEPPIR'),
        ('SEJUV',      'SEJUV'),
        ('SPM',        'SPM'),
        ('CPDH',       'CPDH'),
        ('CORDE',      'CORDE'),
        ('ASJUR',      'ASJUR'),
        ('UIAG',       'UIAG'),
        ('UIFP',       'UIFP'),
    ]

    VEICULOS_CHOICES = [
        ('Carro (4 lugares)', 'Carro (4 lugares)'),
        ('Carro (6 lugares)', 'Carro (6 lugares)'),
        ('Ônibus', 'Ônibus'),
    ]

    setor = models.CharField(
        max_length=12,
        choices=SETOR_CHOICES,
        verbose_name='Setor'
    )
    destino = models.CharField(max_length=100)
    data_ida = models.DateField()
    local_partida = models.TextField(default='SEMJIDH')
    horario_ida = models.TimeField(null=True, blank=True, verbose_name='Horário de ida')
    data_volta = models.DateField()
    horario_volta = models.TimeField(null=True, blank=True, verbose_name='Previsão de retorno')
    servidores = models.TextField()
    motorista = models.ForeignKey(Motorista, null=True, blank=True, on_delete=models.SET_NULL)
    solicitante = models.CharField(null=False, blank=False, max_length=30)
    processo = models.CharField(blank=True, null=True, max_length=23)
    status = models.CharField(
        max_length=20,
        choices=[('Pendente', 'Pendente'), ('Atribuída', 'Atribuída'), ('Concluída', 'Concluída')],
        default='Pendente'
    )
    criada_em = models.DateTimeField(auto_now_add=True)
    veiculo = models.CharField(
        max_length=20,
        choices=VEICULOS_CHOICES,
        verbose_name='Veículo'
    )
    carro = models.ForeignKey(Carro, null=True, blank=True, max_length=200, on_delete=models.SET_NULL)

    @property
    def servidores_lista(self):
        return self.servidores.split(',')

    def __str__(self):
        return f"{self.destino} - {self.data_ida}"

semjidhapp/viagens/forms.py
from django import forms
from .models import Viagem, Motorista, Carro

class ViagemForm(forms.ModelForm):
    class Meta:
        model = Viagem
        fields = ['destino', 'veiculo','data_ida', 'local_partida', 'horario_ida', 'data_volta', 'horario_volta', 'servidores', 'setor', 'solicitante', 'processo']
        widgets = {
            'destino': forms.TextInput(attrs={
                'placeholder': 'Digite para onde será a viagem',
                'type': 'text',
                'class': 'form-control'
            }),
            'veiculo': forms.Select(attrs={
                'class': 'form-select'
            }),
            'data_ida': forms.DateInput(format='%d/%m/%Y', attrs={
                'placeholder': 'DD/MM/YYYY',
                'type': 'text',
                'class': 'form-control'
            }),
            'local_partida': forms.TextInput(attrs={
                'placeholder': 'Qual ponto inicial da viagem?',
                'type': 'text',
                'class': 'form-control'
            }),
            'horario_ida': forms.TimeInput(format='%H:%M', attrs={
                'placeholder': 'HH:MM',
                'type': 'time',
                'class': 'form-control'
            }),
            'data_volta': forms.DateInput(format='%d/%m/%Y', attrs={
                'placeholder': 'DD/MM/YYYY',
                'type': 'text',
                'class': 'form-control'
            }),
            'horario_volta': forms.TimeInput(format='%H:%M', attrs={
                'placeholder': 'HH:MM',
                'type': 'time',
                'class': 'form-control'
            }),
            'servidores': forms.TextInput(attrs={
                'placeholder': 'Digite os nomes dos servidores separados por vírgula',
                'class': 'form-control'
            }),
            'setor': forms.Select(attrs={
                'class': 'form-select'
            }),
            'solicitante': forms.TextInput(attrs={
                'placeholder': 'Digite o nome do solicitante',
                'class': 'form-control'
            }),
            'processo': forms.TextInput(attrs={
                'placeholder': 'Digite o número de processo, se houver',
                'class': 'form-control'
            })
        }
        processo = forms.CharField(required=False)

class MotoristaForm(forms.ModelForm):
    class Meta:
        model = Motorista
        fields = ['nome', 'email']
        widgets = {
            'nome': forms.TextInput(attrs={
                'placeholder': 'Nome do Motorista',
                'class': 'form-control'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email do Motorista',
                'class': 'form-control'
            })
        }

class CarroForm(forms.ModelForm):
    class Meta:
        model = Carro
        fields = ['marca', 'modelo', 'placa']
        widgets = {
            'marca': forms.TextInput(attrs={
                'placeholder': 'Marca do carro',
                'class': 'form-control'
            }),
            'modelo': forms.TextInput(attrs={
                'placeholder': 'Modelo do carro',
                'class': 'form-control'
            }),
            'placa': forms.TextInput(attrs={
                'placeholder': 'Placa do carro',
                'class': 'form-control'
            })
        }

semjidhapp/viagens/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Viagem, Motorista, Carro
from .forms import ViagemForm, MotoristaForm, CarroForm
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse
import csv
from django.core.paginator import Paginator

@login_required
def listar_viagens(request):
    viagens = Viagem.objects.select_related('motorista').order_by('-data_ida')

    # Paginação: 20 viagens por página
    paginator = Paginator(viagens, 20)
    page_number = request.GET.get('page') or 1
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'paginator': paginator,  # necessário para o dropdown
    }
    return render(request, 'viagens/listar_viagens.html', context)

def solicitar_viagem(request):
    if request.method == 'POST':
        form = ViagemForm(request.POST)
        if form.is_valid():
            form.save() 
            messages.success(request, 'Viagem solicitada com sucesso!') 
            return render(request, 'viagens/solicitar_viagem.html', {'form': form}) 
    else:
        form = ViagemForm()
    
    return render(request, 'viagens/solicitar_viagem.html', {'form': form})

@login_required
def designar_motorista(request, viagem_id):
    viagem = Viagem.objects.get(id=viagem_id)
    motoristas = Motorista.objects.all()
    if request.method == 'POST':
        motorista_id = request.POST.get('motorista')
        motorista = Motorista.objects.get(id=motorista_id)
        viagem.motorista = motorista
        viagem.status = 'Atribuída'
        viagem.save()

        assunto = "VIAGEM SOLICITADA!"
        corpo_email = f""" 
                Você foi designado para a seguinte viagem:

                Destino: {viagem.destino}
                Data de ida: {viagem.data_ida.strftime('%d/%m/%Y')}
                Data de volta: {viagem.data_volta.strftime('%d/%m/%Y')}
                Solicitante: {viagem.solicitante}

                Favor confirmar sua disponibilidade.
                """
        
        send_mail(
            assunto,
            corpo_email,
            settings.DEFAULT_FROM_EMAIL,
            [motorista.email],
            fail_silently=False,
        )
        messages.success(request, 'Motorista designado com sucesso e notificado por e-mail!')
        return redirect('listar_viagens')
    return render(request, 'viagens/designar_motorista.html', {'viagem': viagem, 'motoristas': motoristas})

@login_required
def cadastrar_motorista(request):
    if request.method == 'POST':
        form = MotoristaForm(request.POST)
        if form.is_valid():
            form.save()  # Salva o motorista no banco de dados
            
            messages.success(request, 'Motorista cadastrado com sucesso!')
            return redirect('listar_motoristas')  # Redireciona para a página de listagem dos motoristas
    else:
        form = MotoristaForm()
    
    return render(request, 'viagens/cadastrar_motorista.html', {'form': form})

@login_required
def listar_motoristas(request):
    motoristas = Motorista.objects.all()
    return render(request, 'viagens/listar_motorista.html', {'motoristas': motoristas})

def home(request):
    return render(request, 'home.html')

@login_required
def apagar_viagem(request, id):
    viagem = get_object_or_404(Viagem, id=id)

    if request.method == 'POST':
        # Armazena os dados necessários antes de deletar a viagem
        data_ida_str = viagem.data_ida.strftime('%d/%m/%Y')
        destino = viagem.destino
        # Verifica se há motorista associado e obtém o e-mail, se existir
        motorista_email = viagem.motorista.email if viagem.motorista else None

        # Deleta a viagem
        viagem.delete()

        # Se a viagem estiver designada (ou seja, tiver motorista), envia o e-mail
        if motorista_email:
            assunto = "VIAGEM CANCELADA!"
            corpo_email = (
                f"Uma viagem foi cancelada.\n"
                f"Viagem do dia {data_ida_str} de destino {destino} foi cancelada."
            )
            send_mail(
                assunto,
                corpo_email,
                settings.DEFAULT_FROM_EMAIL,
                [motorista_email],
                fail_silently=False,
            )
        return redirect('listar_viagens')  # Redireciona para a lista de viagens

    # Para requisições GET, exibe a tela de confirmação
    return render(request, 'confirmar_apagar.html', {'viagem': viagem})

@login_required
def apagar_motorista(request, id):
    motorista = get_object_or_404(Motorista, id=id)

    if request.method == 'POST':
        motorista.delete()
        return redirect('listar_motoristas')
    

@login_required
def exportar_viagens(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="viagens_semjidh.csv"'

    writer = csv.writer(response)
    
    writer.writerow(['ID', 'Destino', 'Data de Ida', 'Data de Volta', 'Solicitante', 'Motorista'])

    viagens = Viagem.objects.all()

    for viagem in viagens:
        writer.writerow([
            viagem.id,
            viagem.destino,
            viagem.data_ida.strftime('%d/%m/%Y'),  # Formatação da data
            viagem.data_volta.strftime('%d/%m/%Y'),
            viagem.solicitante,
            viagem.motorista.nome if viagem.motorista else 'Sem motorista' 
        ])

    return response

@login_required
def cadastrar_carro(request):
    if request.method == 'POST':
        form = CarroForm(request.POST)
        if form.is_valid():
            form.save()  # Salva o carro no banco de dados
            
            messages.success(request, 'Carro cadastrado com sucesso!')
            return redirect('listar_carros')  # Redireciona para a página de listagem dos carro
    else:
        form = CarroForm()
    
    return render(request, 'viagens/cadastrar_carro.html', {'form': form})

@login_required
def listar_carros(request):
    carros = Carro.objects.all()
    return render(request, 'viagens/listar_carro.html', {'carros': carros})

@login_required
def apagar_carro(request, id):
    carro = get_object_or_404(Carro, id=id)

    if request.method == 'POST':
        carro.delete()
        return redirect('listar_carros')

@login_required
def designar_carro(request, viagem_id):
    viagem = Viagem.objects.get(id=viagem_id)
    carros = Carro.objects.all()
    if request.method == 'POST':
        carro_id = request.POST.get('carro')
        carro = Carro.objects.get(id=carro_id)
        viagem.carro = carro
        viagem.status = 'Atribuída'
        viagem.save()
        messages.success(request, 'Carro designado com sucesso!')
        return redirect('listar_viagens')
    return render(request, 'viagens/designar_carro.html', {'viagem': viagem, 'carros': carros})

semjidhapp/viagens/templates/viagens/base_generic.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sistema de Viagens{% endblock %}</title>

    {% load static %}
    <!-- Link para os arquivos CSS -->
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .logo-container {
            display: flex;
            justify-content: center;
            width: 100%;
        }
    </style>
</head>
<body>
    <header class="bg-light py-3">
        <!-- Container modificado para centralizar a logo -->
        <div class="container">
            <div class="logo-container">
                <img src="{% static 'images/logo_600.png' %}" alt="Logo da Secretaria" width="300">
            </div>
        </div>
    
        <!-- Menu de navegação -->
        <nav>
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cadastrar_motorista' %}">Cadastrar Motorista</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listar_motoristas' %}">Listar Motoristas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cadastrar_carro' %}">Cadastrar Carro</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listar_carros' %}">Listar Carros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listar_viagens' %}">Listar Viagens</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'exportar_viagens' %}" role="button">Exportar Viagens</a>
                </li>
            </ul>
        </nav>
    </header>

    <main>
        <!-- Aqui o conteúdo de cada página específica será inserido -->
        {% block content %}{% endblock %}
    </main>

    <footer class="text-center py-3">
        <p>&copy; 2025 Sistema de Viagens</p>
    </footer>
</body>
</html>

semjidhapp/viagens/templates/viagens/cadastrar_carro.html
{% extends 'viagens/base_generic.html' %}

{% block title %}SEMJIDH - Cadastrar Carros{% endblock %}

{% block content %}
  <div class="container py-4">
    <h2 class="text-dark">Cadastrar Carro</h2>

    <!-- Exibindo mensagens de erro ou sucesso -->
    {% if messages %}
      <ul class="list-unstyled">
        {% for message in messages %}
          <li class="alert alert-info">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    
    <!-- Formulário -->
    <form method="post" class="mt-4">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.as_p }}
      </div>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Cadastrar</button>
      </div>
    </form>
  </div>
{% endblock %}

semjidhapp/viagens/templates/viagens/cadastrar_motorista.html
{% extends 'viagens/base_generic.html' %}

{% block title %}SEMJIDH - Cadastrar Motorista{% endblock %}

{% block content %}
  <div class="container py-4">
    <h2 class="text-dark">Cadastrar Motorista</h2>

    <!-- Exibindo mensagens de erro ou sucesso -->
    {% if messages %}
      <ul class="list-unstyled">
        {% for message in messages %}
          <li class="alert alert-info">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    
    <!-- Formulário -->
    <form method="post" class="mt-4">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.as_p }}
      </div>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Cadastrar</button>
      </div>
    </form>
  </div>
{% endblock %}

semjidhapp/viagens/templates/viagens/designar_carro.html
{% extends 'viagens/base_generic.html' %}

{% block title %}SEMJIDH - Designar Carro{% endblock %}

{% block content %}
  <div class="container py-4">
    <h2 class="text-dark mb-4">Designar Carro para a Viagem: <strong>{{ viagem.destino }}</strong></h2>

    {% if carros %}
      <form method="post" class="bg-white p-4 rounded shadow-sm">
        {% csrf_token %}
        
        <div class="mb-3">
          <label for="carro" class="form-label">Selecione um Carro:</label>
          <select name="carro" id="carro" class="form-select" required>
            <option value="" disabled selected>Selecione um carro</option>
            {% for carro in carros %}
              <option value="{{ carro.id }}">{{ carro }}</option>
            {% endfor %}
          </select>
        </div>

        <div class="d-flex justify-content-center">
          <button type="submit" class="btn btn-primary">Designar</button>
        </div>
      </form>
    {% else %}
      <div class="alert alert-warning">
        Nenhum carro disponível no momento.
      </div>
    {% endif %}
  </div>
{% endblock %}

semjidhapp/viagens/templates/viagens/designar_motorista.html
{% extends 'viagens/base_generic.html' %}

{% block title %}SEMJIDH - Designar Motorista{% endblock %}

{% block content %}
  <div class="container py-4">
    <h2 class="text-dark mb-4">Designar Motorista para a Viagem: <strong>{{ viagem.destino }}</strong></h2>

    <form method="post" class="bg-white p-4 rounded shadow-sm">
      {% csrf_token %}
      
      <!-- Selecione um Motorista -->
      <div class="mb-3">
        <label for="motorista" class="form-label">Selecione um Motorista:</label>
        <select name="motorista" id="motorista" class="form-select">
          {% for motorista in motoristas %}
            <option value="{{ motorista.id }}">{{ motorista.nome}}</option>
          {% endfor %}
        </select>
      </div>

      <!-- Botão para enviar -->
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Designar</button>
      </div>
    </form>
  </div>
{% endblock %}

semjidhapp/viagens/templates/viagens/listar_carro.html
{% extends 'viagens/base_generic.html' %}

{% block title %}SEMJIDH - Listar Carrps{% endblock %}

{% block content %}
  <div class="container py-4">
    <h2 class="text-dark">Lista de Carros</h2>

    <!-- Lista de motoristas -->
    <ul class="list-group mt-4">
      {% for carro in carros %}
        <li class="list-group-item bg-light text-dark d-flex justify-content-between align-items-center mb-3">
          <div>
            <strong>{{ carro }}</strong>
          </div>

          <!-- Formulário para apagar o motorista -->
          <form action="{% url 'apagar_carro' carro.id %}" method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Apagar</button>
          </form>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

semjidhapp/viagens/templates/viagens/listar_motorista.html
{% extends 'viagens/base_generic.html' %}

{% block title %}SEMJIDH - Listar Motoristas{% endblock %}

{% block content %}
  <div class="container py-4">
    <h2 class="text-dark">Lista de Motoristas</h2>

    <!-- Lista de motoristas -->
    <ul class="list-group mt-4">
      {% for motorista in motoristas %}
        <li class="list-group-item bg-light text-dark d-flex justify-content-between align-items-center mb-3">
          <div>
            <strong>{{ motorista.nome }}</strong> - {{ motorista.email }}
          </div>

          <!-- Formulário para apagar o motorista -->
          <form action="{% url 'apagar_motorista' motorista.id %}" method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Apagar</button>
          </form>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

semjidhapp/viagens/templates/viagens/solicitar_viagem.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEMJIDH - Solicitar Viagem</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <!-- Centralizando a logo com Flexbox -->
        <div class="d-flex justify-content-center">
            <img src="{% static 'images/logo_600.png' %}" alt="Logo da Secretaria" width="300">
        </div>
    </header>

    {% if messages %}
        <div class="alert alert-info" role="alert">
            <ul>
                {% for message in messages %}
                    <li class="message">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <!-- Centralizando o conteúdo com flexbox -->
    <div class="container d-flex justify-content-center align-items-center min-vh-100">
        <div class="col-md-6 col-lg-4">
            <h2 class="mb-3 text-center">Solicitar Viagem</h2>

            <form method="post">
                {% csrf_token %}
                
                <!-- Formulário com Bootstrap -->
                <div class="mb-3">
                    <label for="id_destino" class="form-label">Destino:</label>
                    {{ form.destino }}
                    {% if form.destino.errors %}
                        <div class="text-danger">
                            {% for error in form.destino.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_veiculo" class="form-label">Veiculo Solicitado:</label>
                    {{ form.veiculo }}
                    {% if form.veiculo.errors %}
                        <div class="text-danger">
                            {% for error in form.veiculo.errors %}
                                <p> {{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_local_partida" class="form-label">Local de saída:</label>
                    {{ form.local_partida }}
                    {% if form.local_partida.errors %}
                        <div class="text-danger">
                            {% for error in form.local_partida.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_data_ida" class="form-label">Data de Saída:</label>
                    {{ form.data_ida }}
                    {% if form.data_ida.errors %}
                        <div class="text-danger">
                            {% for error in form.data_ida.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_horario_ida" class="form-label">Horario de Saída:</label>
                    {{ form.horario_ida }}
                    {% if form.horario_ida.errors %}
                        <div class="text-danger">
                            {% for error in form.horario_ida.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_data_volta" class="form-label">Data de Volta:</label>
                    {{ form.data_volta }}
                    {% if form.data_volta.errors %}
                        <div class="text-danger">
                            {% for error in form.data_volta.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_horario_volta" class="form-label">Previsão do Horario da volta:</label>
                    {{ form.horario_volta }}
                    {% if form.horario_volta.errors %}
                        <div class="text-danger">
                            {% for error in form.horario_volta.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_servidores" class="form-label">Servidores:</label>
                    {{ form.servidores }}
                    {% if form.servidores.errors %}
                        <div class="text-danger">
                            {% for error in form.servidores.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_setor" class="form-label">Setor requisitante:</label>
                    {{ form.setor }}
                    {% if form.setor.errors %}
                        <div class="text-danger">
                            {% for error in form.setor.errors %}
                                <p> {{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_solicitante" class="form-label">Solicitante:</label>
                    {{ form.solicitante }}
                    {% if form.solicitante.errors %}
                        <div class="text-danger">
                            {% for error in form.solicitante.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-3">
                    <label for="id_processo" class="form-label">Processo:</label>
                    {{ form.processo }}
                    {% if form.processo.errors %}
                        <div class="text-danger">
                            {% for error in form.processo.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Botão de enviar com estilo -->
                <button type="submit" class="btn btn-primary w-100">Solicitar</button>
            </form>
        </div>
    </div>

    <!-- Adicionando o script do Bootstrap no final para funcionalidades como modais ou dropdowns -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>